export * from './Services/Authentication/Controllers/AdminAuthenticationController'
export * from './Services/Authentication/Controllers/ClientAuthenticationController'
export * from './Services/User/Controllers/UserController'
export * from './Services/Category/Controllers/CategoryController'
export * from './Services/Client/Controllers/ClientController'
export * from './Services/Movie/Controllers/MovieController'
export * from './Services/Celebrity/Controllers/CelebrityController'