export * from './login/admin.login.controller'
export * from './login/client.login.controller'
export * from './Login/client.register.controller'
export * from './category.controller'
export * from './user.controller'
export * from './person.controller'
export * from './client.controller'
export * from './movie.controller'